title: TIPE
author: Quentin Fortier

execute:
  execute_notebooks: 'off'

html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://fortierq.github.io/tipe
  extra_navbar: ""

repository:
  url: https://github.com/fortierq/tipe 
  path_to_book: files
  branch: main

launch_buttons:
  basthon_url: "https://notebook.basthon.fr"

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath